/// bat adapter — generates the `theme.zsh` snippet that sets bat's theme.
///
/// bat is a special case. The `BAT_THEME` environment variable overrides bat's
/// own config-file `--theme`, so the reliable way to drive bat from a shell
/// setup is to export `BAT_THEME`. Chroma writes a small generated file
/// (`~/.config/chroma/theme.zsh`, placed by the M4 ApplyEngine) that the user
/// `source`s from `.zshrc`. Like `SketchyBarAdapter`, this is a generate-whole-
/// file adapter that ignores `current` — but unlike SketchyBar it needs no
/// colors, just the theme *name* from `toolNames["bat"]`.
public struct BatAdapter: ThemeAdapter {
    public let toolName = "bat"

    public init() {}

    public func render(theme: Theme, current: String?) throws -> String {
        guard let themeName = theme.toolNames[toolName] else {
            throw AdapterError.missingToolName(tool: toolName, theme: theme.id)
        }

        return """
        # Generated by Chroma — do not edit; regenerated on each theme apply.
        export BAT_THEME="\(themeName)"
        """
    }
}
