/// bat env adapter — exports the `BAT_THEME` that points bat at Chroma's theme.
///
/// bat is a special case. The `BAT_THEME` environment variable overrides bat's
/// own config-file `--theme`, so the reliable way to drive bat from a shell
/// setup is to export `BAT_THEME`. Chroma writes a small generated file
/// (`~/.config/chroma/theme.zsh`, placed by the ApplyEngine) that the user
/// `source`s from `.zshrc`.
///
/// The value is the **constant** `"Chroma"`: `BatThemeAdapter` generates a
/// `Chroma.tmTheme` from the palette on every apply, so bat renders the current
/// theme without this file ever changing. That makes this a one-time setup file
/// (a no-op on every apply after the first) — but Chroma keeps owning it so the
/// wiring is never left half-done. The theme name is intentionally *not* taken
/// from `toolNames`: bat no longer depends on any upstream built-in.
public struct BatAdapter: ThemeAdapter {
    public let toolName = "bat-env"

    /// The bat theme name Chroma always generates and selects.
    public static let themeName = "Chroma"

    public init() {}

    public func render(theme: Theme, current: String?) throws -> String {
        """
        # Generated by Chroma — do not edit; regenerated on each theme apply.
        export BAT_THEME="\(Self.themeName)"
        """
    }
}
