/// SketchyBar adapter — generates the `chroma-palette.sh` file SketchyBar sources.
///
/// SketchyBar has no built-in themes; its idiomatic setup is a shell file,
/// `source`d from `sketchybarrc`, that exports each color as an `0xAARRGGBB`
/// value. The naïve approach is to generate the user's whole `colors.sh` — but
/// that file is the *user's*: it also holds `$FONT`, derived tokens
/// (`BAR_COLOR`/`PILL_*`/`HOVER_BORDER`/`POPUP_COLOR`), and upstream palette
/// names. Overwriting it wholesale violates PLAN's "respect the real config
/// owner" principle and silently drops everything Chroma didn't know about.
///
/// So, exactly like `BatAdapter`, Chroma owns a **separate** generated file and
/// never touches the user's. This file exports the 17 semantic roles under a
/// `CHROMA_` namespace (so they can't collide with the user's own `RED`,
/// `MAUVE`, `FONT`, …). The user edits their `colors.sh` *once* to `source` it
/// and map their names onto the roles, e.g.:
///
/// ```sh
/// source "$CONFIG_DIR/chroma-palette.sh"
/// export MAUVE=$CHROMA_PURPLE   # keep your own names, fed by Chroma
/// export TEAL=$CHROMA_CYAN
/// export PEACH=$CHROMA_ORANGE
/// # FONT, BAR_COLOR, PILL_*, … stay yours, untouched
/// ```
///
/// Re-theming then regenerates only Chroma's file and reloads; the user's font,
/// derived tokens, and layout survive every apply.
public struct SketchyBarAdapter: ThemeAdapter {
    public let toolName = "sketchybar"

    public init() {}

    public func render(theme: Theme, current: String?) throws -> String {
        // `current` is intentionally unused: this file is fully owned by Chroma,
        // so it is regenerated wholesale on every apply. That's safe *because*
        // it's Chroma's file, not the user's — see the type doc.
        try TemplateRenderer.render(Self.template, palette: theme.palette)
    }

    /// The `chroma-palette.sh` template. Each `{{role:argb}}` becomes
    /// `0xAARRGGBB`. Names are `CHROMA_`-prefixed to stay out of the user's
    /// namespace; consumers map them onto their own vars (see the type doc).
    private static let template = """
    #!/usr/bin/env bash
    # Generated by Chroma — do not edit. Chroma owns this file and rewrites it on
    # every theme apply. Source it from your colors.sh and map CHROMA_* onto your
    # own color names; keep your $FONT and derived tokens in colors.sh.

    export CHROMA_BASE={{base:argb}}
    export CHROMA_MANTLE={{mantle:argb}}
    export CHROMA_CRUST={{crust:argb}}
    export CHROMA_SURFACE0={{surface0:argb}}
    export CHROMA_SURFACE1={{surface1:argb}}
    export CHROMA_SURFACE2={{surface2:argb}}
    export CHROMA_OVERLAY={{overlay:argb}}
    export CHROMA_TEXT={{text:argb}}
    export CHROMA_TEXT_MUTED={{textMuted:argb}}
    export CHROMA_RED={{red:argb}}
    export CHROMA_ORANGE={{orange:argb}}
    export CHROMA_YELLOW={{yellow:argb}}
    export CHROMA_GREEN={{green:argb}}
    export CHROMA_CYAN={{cyan:argb}}
    export CHROMA_BLUE={{blue:argb}}
    export CHROMA_PURPLE={{purple:argb}}
    export CHROMA_PINK={{pink:argb}}
    """
}
