/// SketchyBar adapter — generates the `colors.sh` file SketchyBar sources.
///
/// SketchyBar has no built-in themes. Its idiomatic setup is a `colors.sh`
/// file, `source`d from `sketchybarrc`, that exports each color as an
/// `0xAARRGGBB` value. So unlike `GhosttyAdapter`/`ZellijAdapter` — which edit a
/// single line of an existing config — this adapter *ignores* the current file
/// and regenerates the whole thing from a template. That's exactly what
/// `TemplateRenderer` is for, and why the placeholders use the `:argb` format.
public struct SketchyBarAdapter: ThemeAdapter {
    public let toolName = "sketchybar"

    public init() {}

    public func render(theme: Theme, current: String?) throws -> String {
        // `current` is intentionally unused: this file is fully generated, so
        // whatever was there before is replaced wholesale on every apply.
        try TemplateRenderer.render(Self.template, palette: theme.palette)
    }

    /// The `colors.sh` template. Each `{{role:argb}}` becomes `0xAARRGGBB`.
    /// Consumers reference the exported names (e.g. `$RED`) in their bar items.
    private static let template = """
    #!/usr/bin/env bash
    # Generated by Chroma — do not edit; regenerated on each theme apply.

    export BASE={{base:argb}}
    export MANTLE={{mantle:argb}}
    export CRUST={{crust:argb}}
    export SURFACE0={{surface0:argb}}
    export SURFACE1={{surface1:argb}}
    export SURFACE2={{surface2:argb}}
    export OVERLAY={{overlay:argb}}
    export TEXT={{text:argb}}
    export TEXT_MUTED={{textMuted:argb}}
    export RED={{red:argb}}
    export ORANGE={{orange:argb}}
    export YELLOW={{yellow:argb}}
    export GREEN={{green:argb}}
    export CYAN={{cyan:argb}}
    export BLUE={{blue:argb}}
    export PURPLE={{purple:argb}}
    export PINK={{pink:argb}}
    """
}
