/// Spicetify adapter — generates the `color.ini` that themes Spotify.
///
/// Spicetify injects CSS into the Spotify client from a theme folder whose
/// `color.ini` maps a fixed set of UI keys (`main`, `text`, `player`, …) to
/// colors, grouped under one or more named *color schemes*. Chroma generates a
/// single scheme, `[chroma]`, from the palette for every theme; the user points
/// Spicetify at it once (`spicetify config current_theme Chroma color_scheme
/// chroma`) and `spicetify apply` re-patches Spotify on each re-theme.
///
/// Like `BatThemeAdapter`, this is a generate-whole-file adapter: it owns the
/// file and ignores `current`. Every color resolves through the palette
/// fallback chain, so shallow palettes still produce a complete scheme. Unlike
/// most tools, Spicetify wants **bare** hex (`main = 303446`, no leading `#`),
/// so each value is emitted via `Self.bare(_:)`. The key set below is
/// Spicetify's standard roster; `button-active`, `tab-active`, and `equalizer`
/// lead with the theme's primary accent (`palette.accent`).
public struct SpicetifyAdapter: ThemeAdapter {
    public let toolName = "spicetify"

    public init() {}

    public func render(theme: Theme, current: String?) throws -> String {
        // `current` is intentionally unused: Chroma owns this file and rewrites
        // it wholesale on every apply — see the type doc.
        let palette = theme.palette

        func role(_ role: ColorRole) -> String { Self.bare(palette[role]) }
        let accent = Self.bare(palette.accent)

        return """
        ; Generated by Chroma — do not edit; regenerated on each theme apply.
        [chroma]
        text                = \(role(.text))
        subtext             = \(role(.textMuted))
        main                = \(role(.base))
        main-elevated       = \(role(.surface0))
        highlight           = \(role(.surface1))
        highlight-elevated  = \(role(.surface2))
        sidebar             = \(role(.mantle))
        player              = \(role(.mantle))
        card                = \(role(.surface0))
        shadow              = \(role(.crust))
        selected-row        = \(role(.overlay))
        button              = \(role(.overlay))
        button-active       = \(accent)
        button-disabled     = \(role(.overlay))
        tab-active          = \(accent)
        notification        = \(role(.surface0))
        notification-error  = \(role(.red))
        equalizer           = \(accent)
        misc                = \(role(.surface2))
        """
    }

    /// Spicetify wants bare 6-digit hex (`303446`), not `#303446` — drop the
    /// leading `#` that `HexColor.hexString` emits.
    private static func bare(_ color: HexColor) -> String {
        String(color.hexString.dropFirst())
    }
}
