/// Starship adapter — ensures the theme's palette table exists, then selects it.
///
/// Starship's theming model is to define palette tables in `starship.toml`
/// (`[palettes.catppuccin_mocha]`, …) and switch between them with a single
/// top-level `palette = "…"` line. Catppuccin ships all four tables by hand, so
/// for those we only rewrite that one line.
///
/// For every *other* family (Nord, Tokyo Night, …) the table doesn't exist yet.
/// Rather than make the user hand-author one per theme, this adapter **generates
/// the `[palettes.<name>]` table from Chroma's semantic roles** and appends it if
/// absent — using **Catppuccin's key names** (`mauve`, `lavender`, `surface0`,
/// `subtext0`, …). That's deliberate: the user's prompt `format` already
/// references those Catppuccin names, so a generated table lets any theme drive
/// the existing prompt with zero edits to the modules. Appending is idempotent —
/// a table that's already present (the four Catppuccin ones, or a
/// previously-generated one) is left untouched.
public struct StarshipAdapter: ThemeAdapter {
    public let toolName = "starship"

    public init() {}

    public func render(theme: Theme, current: String?) throws -> String {
        guard let paletteName = theme.toolNames[toolName] else {
            throw AdapterError.missingToolName(tool: toolName, theme: theme.id)
        }

        // 1. Ensure the palette table exists. Catppuccin's four are hand-authored
        //    (and any theme applied before is already here) → skip. Anything else
        //    gets a generated table mapped from roles.
        var content = current ?? ""
        if !Self.hasPaletteTable(named: paletteName, in: content) {
            content = Self.appendingPaletteTable(named: paletteName, palette: theme.palette, to: content)
        }

        // 2. Switch the active palette by rewriting the single top-level line.
        let newLine = "palette = \"\(paletteName)\""
        return try ConfigLineEditor.replacingLine(
            in: content,
            with: newLine,
            anchorLabel: "palette = \"…\"",
            where: Self.isPaletteLine
        )
    }

    /// True when `line` is an active top-level `palette = "…"` assignment.
    private static func isPaletteLine(_ line: String) -> Bool {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard !trimmed.hasPrefix("#") else { return false }
        guard let equals = trimmed.firstIndex(of: "=") else { return false }
        return trimmed[..<equals].trimmingCharacters(in: .whitespaces) == "palette"
    }

    /// True when a `[palettes.<name>]` table header is already in the config.
    static func hasPaletteTable(named name: String, in content: String) -> Bool {
        let header = "[palettes.\(name)]"
        return content
            .split(separator: "\n", omittingEmptySubsequences: false)
            .contains { $0.trimmingCharacters(in: .whitespaces) == header }
    }

    /// Chroma role → Catppuccin palette key names. One role can feed several
    /// Catppuccin names (Chroma models 17 roles; Catppuccin exposes ~26) so any
    /// name a user's prompt references resolves — extras collapse onto the
    /// nearest role through the palette's fallback subscript.
    static let catppuccinKeyForRole: [(key: String, role: ColorRole)] = [
        ("rosewater", .pink), ("flamingo", .red), ("pink", .pink), ("mauve", .purple),
        ("red", .red), ("maroon", .red), ("peach", .orange), ("yellow", .yellow),
        ("green", .green), ("teal", .cyan), ("sky", .cyan), ("sapphire", .blue),
        ("blue", .blue), ("lavender", .blue), ("text", .text),
        ("subtext1", .textMuted), ("subtext0", .textMuted),
        ("overlay2", .overlay), ("overlay1", .overlay), ("overlay0", .overlay),
        ("surface2", .surface2), ("surface1", .surface1), ("surface0", .surface0),
        ("base", .base), ("mantle", .mantle), ("crust", .crust),
    ]

    /// Append a generated `[palettes.<name>]` table (Catppuccin-keyed, resolved
    /// through the fallback subscript) to `content`.
    static func appendingPaletteTable(named name: String, palette: Palette, to content: String) -> String {
        var block = "\n# Generated by Chroma — palette \"\(name)\" mapped from semantic roles.\n"
        block += "[palettes.\(name)]\n"
        for (key, role) in catppuccinKeyForRole {
            block += "\(key) = \"\(palette[role].hexString)\"\n"
        }
        // Guarantee exactly one blank line between prior content and the table.
        let base = content.hasSuffix("\n") ? String(content.dropLast()) : content
        return base + "\n" + block
    }
}
